### ISSUE TITLE
Check if user admin token created has correct ACL

### ISSUE THREAD

**Issue by FredericMartinez** [opengento/magento2-better-bo#6]
Check if user admin token created has correct ACL in `Observer/AdminLoginCookie.php`

```
$context = new CustomUserContext(
            (int) $user->getId(),
            CustomUserContext::USER_TYPE_ADMIN
        );
```

**Comment by THOMASPH2M** [comment]
### Observation 

1. Acl admin user set to access only "catalog" 
2. Test get orders : ` curl --location --globoff 'http://www.magento.code/rest/default/V1/orders?searchCriteria[filterGroups][0][filters][0][field]=entity_id&searchCriteria[filterGroups][0][filters][0][value]=Test%20Auto%20Coupon%2020&searchCriteria[filterGroups][0][filters][0][conditionType]=neq'`
Return orders (not what we want)
3. Logout and Login 
4. Test get orders : ` curl --location --globoff 'http://www.magento.code/rest/default/V1/orders?searchCriteria[filterGroups][0][filters][0][field]=entity_id&searchCriteria[filterGroups][0][filters][0][value]=Test%20Auto%20Coupon%2020&searchCriteria[filterGroups][0][filters][0][conditionType]=neq'`
No return orders (ok)

### Conclusion
The token "better bo"  store in admin extra is ISO with admin user Acl, but we need to refresh better bo token refresh when new Acl are save.
